all::
	echo -------------------- TODO ---------------------

clean::
	echo -------------------- TODO ---------------------
#	-rm *.o

build::
	echo -------------------- TODO ---------------------

test::
	cd test ; lua regress_test.lua 

