BUILD_FILES=MqttUdpTray.jar MqttUdpTray.exe 


all::
	ant -f makeJar.xml 

clean:
	-rm -r bin/*

build:: all
	cp $(BUILD_FILES)  ../../build

test::
	echo -------------------- TODO ---------------------



