BUILD_FILES=uilib.jar


all::
	ant -f makeJava.xml 
	ant -f makeJar.xml 

clean:
	-rm -r bin/*

build:: all
	cp $(BUILD_FILES)  ../../build

test::
	echo -------------------- TODO ---------------------



