/* This code is generated, do not change */
#define PACKAGE_VERSION_MAJOR   0 
#define PACKAGE_VERSION_MINOR   4 
#define PTYPE_CONNECT   0x10 
#define PTYPE_CONNACK   0x20 
#define PTYPE_PUBLISH   0x30 
#define PTYPE_PUBACK   0x40 
#define PTYPE_PUBREC   0x50 
#define PTYPE_PUBREL   0x60 
#define PTYPE_PUBCOMP   0x70 
#define PTYPE_SUBSCRIBE   0x80 
#define PTYPE_SUBACK   0x90 
#define PTYPE_UNSUBSCRIBE   0xA0 
#define PTYPE_UNSUBACK   0xB0 
#define PTYPE_PINGREQ   0xC0 
#define PTYPE_PINGRESP   0xD0 
#define PTYPE_DISCONNECT   0xE0 
#define MQTT_PORT   1883 
#define PKT_BUF_SIZE   2048 
#define PKT_PACE_MSEC   50 
