all::
	echo -------------------- TODO ---------------------

clean::
	echo -------------------- TODO ---------------------
#	-rm *.o

build::
	echo -------------------- TODO ---------------------

test::
	chmod a+rx test/*.py
	cd test ; ./utest_match.py ; ./utest_err_handler.py ; ./utest_signature.py 

