all::
	echo -------------------- TODO ---------------------

clean::
	echo -------------------- TODO ---------------------
#	-rm *.o

build::
	echo -------------------- TODO ---------------------

test::
	cd test ; ./regress_test.py 

