KC=G:\bin\kotlin-native-windows-1.3.11\bin\kotlinc.bat 

SRC=src/ru/dz/mqtt_udp/clock/main.kt 

MQJ=../../../build/mqtt_udp.jar

RT=C:\Program Files\Java\jre1.8.0_192\lib\rt.jar

all::
	$(KC)  $(SRC) $(MQJ) '$(RT)'
