CFLAGS += -g
#CC=gcc

include makedefs


goal:: all

all:: mqtt_udp_pub mqtt_udp_sub mqtt_udp_listen

run::
	./mqtt_udp_sub

clean::
	-rm *.o *.d *.exe *~


mqtt_udp_pub: $(OBJS) mqtt_udp_pub.o
	$(CC) $(CFLAGS) -o $@ $^

mqtt_udp_sub: $(OBJS) mqtt_udp_sub.o
	$(CC) $(CFLAGS) -o $@ $^

mqtt_udp_listen: $(OBJS) mqtt_udp_listen.o
	$(CC) $(CFLAGS) -o $@ $^
