# Makefile for cygwin env.

CFLAGS += -g -O2 -Wall 
# make dependencies files
CFLAGS += -MD -MP 
CC=gcc
AR=ar
RANLIB=ranlib

CFLAGS += -Iarch/default
EXESUFFIX=.exe


goal:: all


LIB=libmqttudp.a
#LIBV=libmqttudp.0.1.a
BUILD_PROGRAMS := true



include makedefs
include makerules

vpath %.c examples
vpath %.c glue/unix



#library:: libmqttudp.a
library:: $(LIB)



-include $(exclude README.md, $(wildcard *.md))
