all::
	echo -------------------- TODO ---------------------

clean::
	echo -------------------- TODO ---------------------
¹	-rm *.o

build::
	echo nothing to do

test::
	echo -------------------- TODO ---------------------


