all::
	echo -------------------- TODO ---------------------

clean::
	echo -------------------- TODO ---------------------
#	-rm *.o

build::
	echo nothing to do

test::
	echo -------------------- TODO ---------------------


